export const LOAD_DATA = 'LOAD_DATA'
export const SAVE_DATA = 'SAVE_DATA'
export const LOAD_LIST = 'LOAD_LIST'

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'
export const UPDATE_TITLE = 'UPDATE_TITLE'

export const SHOW_LINK_EDITOR = 'SHOW_LINK_EDITOR'
export const HIDE_LINK_EDITOR = 'HIDE_LINK_EDITOR'

export const TOGGLE_SUBEDITOR = 'TOGGLE_SUBEDITOR'
